### ISSUE TITLE
Add information to about page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#60]
Please design the about page following the design of https://www.google.com/intl/en/about/

Please add the following information
- [ ] one column
  Our mission is to make the world’s social media information openly accessible and useful generating open knowledge for all. # OpenData (/search?query=#OpenData) #OpenSource (/search?query=#OpenSource) #OpenKnowledge (/search?query=#OpenKnowledge)
- [ ] three columns

News from us
Read up on our latest news and browse our blog (http://blog.loklak.net) for updates on our work. 

Developers
Wanna know how to set up loklak yourself or you would like to develop an app based on loklak. On http://api.loklak.org you find more info about our APIs.

Contribute to our projects
Ever wondered what life as a developers looks like or what benefits you might expect as an Open Source contributor? Search for an issue to solve on our repositories with FOSSASIA (https://github.com/fossasia?utf8=%E2%9C%93&query=loklak) or the loklak org (http://github.com/loklak/) and check out feature requests and issues. 
- [ ] adjust height and use this image
  ![nasa-apollo8-dec24-earthrise](https://cloud.githubusercontent.com/assets/1583873/19458301/7c17c4e6-94cb-11e6-97b3-a0cc78b18c78.jpg)

**Comment by rishiraj824** [comment]
on it @mariobehling. Assign me this.

**Comment by jig08** [comment]
@rishiraj824 Joined the FOSSASIA Codeheat team ?

**Comment by mariobehling** [comment]
@rishiraj824 Please go ahead. Sent you an invite to FOSSASIA. Please accept it, so we can assign you. Cheers.

**Comment by rishiraj824** [comment]
Yeah got it. Thanks @mariobehling

**Comment by mariobehling** [comment]
I am unassigning this as it is sufficient if contributors have one task assigned.

**Comment by sandmanx** [comment]
If this issue is still not fixed, I am willing to take it up.

**Comment by mariobehling** [comment]
Please have a look at the pull request here https://github.com/fossasia/loklak_search/pull/66 and help to fix it, if possible. Thank you.

**Comment by mariobehling** [comment]
@sandmanx Would be great if you want to help. There is an about page here already: http://loklak.fossasia.org/about

Please change as follows:
* [ ] Heading "News from us" -> "About Us"
* [ ] The three columns should be implemented as outlined in the description above (here in this issue): 1. News from us, 2. Developers, 3. Contribute to our projects
* [ ] Heading "Developers" section -> "Contact Us" and below text "If you would like to get in touch with us, please our information is available here (with link to contact form). Additionally, please leave some white space below this text.

**Comment by sandmanx** [comment]
@mariobehling On it with Godspeed!!

**Comment by jig08** [comment]
@sandmanx if you don't mind, I just pushed my changes for the same ?

**Comment by sandmanx** [comment]
@jig08 If the issue is fixed completely, no problem then : )

**Comment by mariobehling** [comment]
Issue is not fixed. Last comments were not taken into account: https://github.com/fossasia/loklak_search/issues/60#issuecomment-256701691

**Comment by rishiraj824** [comment]
@mariobehling please tell me what else needs to be fixed.

**Comment by mariobehling** [comment]
Still wrong text at section:

"News from us
Read up on our latest news and browse our blog (http://blog.loklak.net) for updates on our work."

**Comment by Achint08** [comment]
@mariobehling  Let's close this PR. I am correcting this.
